name = "ucp-demo-server"
main = "src/entry.py"
compatibility_date = "2025-04-10"
compatibility_flags = ["python_workers"]

# Set CLOUDFLARE_ACCOUNT_ID env var or add account_id here
account_id = ""

[vars]
# Install MCP from runtype.com and ask your assistant to:
# "Build me an agent with all the UCP tools, a chat surface, and return a client token I can use use on my site"
RUNTYPE_CLIENT_TOKEN = ""

[[d1_databases]]
binding = "DB"
database_name = "ucp-flower-shop"
database_id = ""
migrations_dir = "migrations"
